// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzCTy6vaFtnSmvG6JBOdSbV8P8fnizMq0',
    appId: '1:318444538082:web:45bf4593c0265c8809b6bb',
    messagingSenderId: '318444538082',
    projectId: 'school-60047',
    authDomain: 'school-60047.firebaseapp.com',
    storageBucket: 'school-60047.appspot.com',
    measurementId: 'G-1ZVRFN79SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHLbwHu1seOWB7GO4zKX9TGT9Wo-LSEyE',
    appId: '1:318444538082:android:ca3bb32d27168b0f09b6bb',
    messagingSenderId: '318444538082',
    projectId: 'school-60047',
    storageBucket: 'school-60047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrXHDpYopjT7wFh9XOLBtuZpwYCOXOahA',
    appId: '1:318444538082:ios:b53b6c4aa566372c09b6bb',
    messagingSenderId: '318444538082',
    projectId: 'school-60047',
    storageBucket: 'school-60047.appspot.com',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrXHDpYopjT7wFh9XOLBtuZpwYCOXOahA',
    appId: '1:318444538082:ios:b53b6c4aa566372c09b6bb',
    messagingSenderId: '318444538082',
    projectId: 'school-60047',
    storageBucket: 'school-60047.appspot.com',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzCTy6vaFtnSmvG6JBOdSbV8P8fnizMq0',
    appId: '1:318444538082:web:81e7e46996ebccde09b6bb',
    messagingSenderId: '318444538082',
    projectId: 'school-60047',
    authDomain: 'school-60047.firebaseapp.com',
    storageBucket: 'school-60047.appspot.com',
    measurementId: 'G-CYTGRTKQQK',
  );
}
